# Generated by Django 5.2.4 on 2025-08-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('church_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_groups.churchgroup')),
            ],
        ),
    ]
