# Generated by Django 5.2.4 on 2025-08-20 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_projects.churchproject')),
            ],
        ),
    ]
