# Generated by Django 5.2.4 on 2025-08-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church')),
            ],
        ),
    ]
